---
- name: Check the presence of the task binary.
  stat:
    path: "{{ task_bin_path }}"
  register: task_check

- name: Check the task version.
  shell: "{{ task_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: task_current_version

- name: Install task v{{ task_version }}
  include_tasks: install.yml
  when: >-
    not task_check.stat.exists
    or task_version not in task_current_version.stdout
